project_id = "gqwymmauiijshudgstva"

[functions.rag-index]
verify_jwt = false

[functions.rag-search]
verify_jwt = false

[functions.compress-snippets]
verify_jwt = false

[functions.agent-route]
verify_jwt = false

[functions.tool-calendar-create]
verify_jwt = false

[functions.tool-contacts]
verify_jwt = false