-- Create telemetry table for LLM usage tracking
CREATE TABLE IF NOT EXISTS llm_stats (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  created_at timestamptz default now(),
  tokens_total int not null,
  mem_items int not null,
  top_score real,
  intent text -- action | recall | mixed
);