// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gqwymmauiijshudgstva.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdxd3ltbWF1aWlqc2h1ZGdzdHZhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0MDI2MzQsImV4cCI6MjA3Mzk3ODYzNH0.GXQ7X4-4ICoSSl7q1-5gtrzv7T8UQ77SaqpdMqCQahk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});